config/routes.rb
Rails.application.routes.draw do

  resources :likes, only: [:create, :destroy]
  resources :cities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :gossips
  root "gossips#index"
  # get "/home", to: "pages#home"
  get "/team", to: "pages#team"
  get "/contact", to: "pages#contact"
  # get "/welcome/:name", to: "pages#welcome"
  # get "/welcome", to: "pages#welcome"
  # get "/tests/:id", to: "pages#gossip"
  # get "/users/:id", to: "pages#user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:update, :new, :create, :edit, :destroy]
  before_action :is_connected, only: [:show]

  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    puts "#" * 30
    puts params
    puts "#" * 30
    @comment = Comment.new
    @commentable_id = params[:commentable_id]
    @commentable_type = params[:commentable_type]
    puts "#" * 30
    puts @commentable_id
    puts @commentable_type
    puts "#" * 30
  end


  def create
    # @comment = Comment.new(title: params[:Comment][:title], content: params[:Comment][:content], user_id: params[:Comment][:user_id]) # avec xxx qui sont les données obtenues à partir du formulaire
    @comment = Comment.new(post_params)
    if @comment.save # essaie de sauvegarder en base @comment
      flash[:success] = "Commentaire bien créé !"
      redirect_to '/'
      # si ça marche, il redirige vers la page d'index du site
    else
      render "new"
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

  def edit
    @comment = Comment.find(params[:id])
    
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(post_params)
    redirect_to comments_path
    flash[:success] = "Commentaire bien modifié"
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to comments_path
    flash[:success] = "Commentaire bien supprimé"
  end

  private

  def post_params
    post_params = params.require(:comment).permit(:content, :user_id, :commentable_id, :commentable_type)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_connected
    unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<% if @comment.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class= "home">
<%= simple_form_for @comment do |f| %>
  <%= f.input :content %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :commentable_id, value: @comment.commentable_id %>
  <%= f.hidden_field :commentable_type, value: @comment.commentable_type %>\
  <%= f.button :submit %>
<% end %>
</div>

app/views/comments/index.html.erb
<h1>Les Commentaires</h1>
<div class="album-cards">
  <% @comments.each do |comment| %>
    <div class="card">
    <h3> <%=comment.content%> </h3>
    <p>Ce commentaire vous est servi par <%=comment.user.name%></p>
    <%= link_to "Afficher le comment", "/comments/#{comment.id}"%>
    </div>
  <%end%>
</div>

app/views/comments/new.html.erb
<% if @comment.errors.any? %>
  <p>Nous n'avons pas réussi à créer le commentaire pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class= "home">
<%= simple_form_for @comment do |f| %>
  <%= f.input :content %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :commentable_type, value: @commentable_type %>
  <%= f.hidden_field :commentable_id, value: @commentable_id %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/comments/show.html.erb
<div class= "home">
  <h1>Commentaire de <%=@comment.user.name%></h1>

  <h3>Commentaire : <%=@comment.content%> </h3>
  <p> <%=@comment.created_at%> </p>
  <% if @comment.commentable_type == "Gossip" %>
  <%= link_to "Afficher la page du potin commenté", gossip_path(id: @comment.commentable_id)%>
  <%end%>
  <% if @comment.commentable_type == "Comment" %>
  <%= link_to "Afficher la page du commentaire commenté", comment_path(id: @comment.commentable_id)%>
  <%end%>
  <%= link_to "Commenter le commentaire", new_comment_path(:commentable_id => @comment.id, :commentable_type => "Comment")%>

  <%= link_to "Afficher la page de l'utilisateur", user_path(id: @comment.user_id)%>
  <% if session[:user_id] == @comment.user_id %>
  <%= link_to "Modifier le commentaire", edit_comment_path(id: @comment.id)%>
  <a href="<%= comment_path(@comment.id) %>" class="btn" data-confirm="êtes-vous sur?" data-method="DELETE">Effacer le commentaire</a>
  <%end%>

</div>

<% if @comment.comments != []%>
  <h1>Les Commentaires</h1>
  <div class="album-cards">
    <% @comment.comments.each do |comment| %>
      <div class="card">
      <h3> <%=comment.content%> </h3>
      <p>Ce commentaire vous est servi par <%=comment.user.name%></p>
      <%= link_to "Afficher le comment", "/comments/#{comment.id}"%>
      </div>
    <%end%>
  </div>
<%end%>