config/routes.rb
Rails.application.routes.draw do

  resources :likes, only: [:create, :destroy]
  resources :cities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :gossips
  root "gossips#index"
  # get "/home", to: "pages#home"
  get "/team", to: "pages#team"
  get "/contact", to: "pages#contact"
  # get "/welcome/:name", to: "pages#welcome"
  # get "/welcome", to: "pages#welcome"
  # get "/tests/:id", to: "pages#gossip"
  # get "/users/:id", to: "pages#user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, length: { minimum: 3 , maximum: 14}
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  
  before_action :authenticate_user, only: [:update, :new, :create, :edit, :destroy]
  before_action :is_connected, only: [:show]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end


  def create
    # @gossip = Gossip.new(title: params[:gossip][:title], content: params[:gossip][:content], user_id: params[:gossip][:user_id]) # avec xxx qui sont les données obtenues à partir du formulaire
    @gossip = Gossip.new(post_params)
    if @gossip.save # essaie de sauvegarder en base @gossip
      flash[:success] = "Potin bien créé !"
      redirect_to '/'
      # si ça marche, il redirige vers la page d'index du site
    else
      render "new"
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    @gossip.update(post_params)
    redirect_to gossip_path
    flash[:success] = "Potin bien modifié"
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
    flash[:success] = "Potin bien supprimé"
  end

  private

  def post_params
    post_params = params.require(:gossip).permit(:title, :content, :user_id)
  end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_connected
    unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/views/gossips/edit.html.erb
<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class= "home">
<%= simple_form_for @gossip do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/gossips/index.html.erb
<h1>The Gossip Project</h1>
<div class="album-cards">
  <% @gossips.each do |gossip| %>
    <div class="card">
    <h3> <%=gossip.title%> </h3>
    <p>Ce gossip vous est servi par <%=gossip.user.name%></p>
    <%= link_to "Afficher le Gossip", "/gossips/#{gossip.id}"%>
    <% if current_user && !current_user.likes.where(likeable_type: 'Gossip', likeable_id: gossip.id).first %>
    <%= link_to "Like !", likes_path(:likeable_id => gossip.id, :likeable_type => "Gossip"), method: :post%>
    <%end%>
    <% if current_user && current_user.likes.where(likeable_type: 'Gossip', likeable_id: gossip.id).first %>
      <a href="<%= like_path(current_user.likes.where(likeable_type: 'Gossip', likeable_id: gossip.id).first.id) %>" class="btn" data-confirm="êtes-vous sur?" data-method="DELETE">Effacer le like</a>
    <%end%>
    <p>Compteur de likes <%=gossip.likes.count%></p>
    </div>
  <%end%>
</div>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>
  <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class= "home">
<%= simple_form_for @gossip do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/gossips/show.html.erb
<div class= "home">
  <h1>Gossip de <%=@gossip.user.name%></h1>

  <h2>Titre : <%=@gossip.title%> </h2>
  <h3>Gossip : <%=@gossip.content%> </h3>
  <p> <%=@gossip.created_at%> </p>
  <%= link_to "Afficher la page de l'utilisateur", user_path(id: @gossip.user_id)%>
  <%= link_to "Commenter le gossip", new_comment_path(:commentable_id => @gossip.id, :commentable_type => "Gossip")%>
  <% if session[:user_id] == @gossip.user_id %>
    <%= link_to "Modifier le potin", edit_gossip_path(id: @gossip.id)%>
    <a href="<%= gossip_path(@gossip.id) %>" class="btn" data-confirm="êtes-vous sur?" data-method="DELETE">Effacer le potin</a>
  <%end%>
  <% if !current_user.likes.where(likeable_type: 'Gossip', likeable_id: @gossip.id).first %>
    <%= link_to "Like !", likes_path(:likeable_id => @gossip.id, :likeable_type => "Gossip"), method: :post%>
  <%end%>
  <% if current_user.likes.where(likeable_type: 'Gossip', likeable_id: @gossip.id).first %>
    <a href="<%= like_path(current_user.likes.where(likeable_type: 'Gossip', likeable_id: @gossip.id).first.id) %>" class="btn" data-confirm="êtes-vous sur?" data-method="DELETE">Effacer le like</a>
  <%end%>
  <p>Compteur de likes <%=@gossip.likes.count%></p>

</div>

<% if @gossip.comments != []%>
  <h1>Les Commentaires</h1>
  <div class="album-cards">
    <% @gossip.comments.each do |comment| %>
      <div class="card">
      <h3> <%=comment.content%> </h3>
      <p>Ce commentaire vous est servi par <%=comment.user.name%></p>
      <%= link_to "Afficher le comment", "/comments/#{comment.id}"%>
      </div>
    <%end%>
  </div>
<%end%>