config/routes.rb
Rails.application.routes.draw do

  resources :likes, only: [:create, :destroy]
  resources :cities
  resources :comments
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :gossips
  root "gossips#index"
  # get "/home", to: "pages#home"
  get "/team", to: "pages#team"
  get "/contact", to: "pages#contact"
  # get "/welcome/:name", to: "pages#welcome"
  # get "/welcome", to: "pages#welcome"
  # get "/tests/:id", to: "pages#gossip"
  # get "/users/:id", to: "pages#user"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, length: { minimum: 3 , maximum: 14}
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/models/gossip_tag_join.rb
class GossipTagJoin < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :private_message_recipient_joins
  has_many :recipients, through: :private_message_recipient_joins
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_joins
  has_many :gossips, through: :gossip_tag_joins
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, length: { minimum: 5 }, uniqueness: true
  validates :password, length: { in: 6..20 }
  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :private_message_recipient_joins
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "private_message_recipient_join"
  has_secure_password
  has_many :likes
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :destroy]

  def create
    # @like = Like.new(title: params[:Like][:title], content: params[:Like][:content], user_id: params[:Like][:user_id]) # avec xxx qui sont les données obtenues à partir du formulaire
    @like = Like.new(likeable_id: params[:likeable_id], user_id: session[:user_id], likeable_type: params[:likeable_type])
    if @like.save # essaie de sauvegarder en base @like
      flash[:success] = "Like bien créé !"
      redirect_to request.referrer
      # si ça marche, il redirige vers la page d'index du site
    else
      render "new"
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

  def destroy
    # @like = Like.find_by(id: params[:id].id)
    @like = Like.find(params[:id])
    @like.destroy
    redirect_to request.referrer
    flash[:success] = "Like bien supprimé"
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

  def is_connected
    unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @gossips = Gossip.all
  end

  def welcome
    if params[:name] == "" || params[:name] == nil
      @name = "Je ne connais pas ton blaze, je n'ai pas pu personnaliser ce message..."
      @path = "=> http://localhost:3000/home/TonBlaze"
    else
      @name = params[:name]
    end
  end

  def team
    @team = ["Tim","Got","Louis","Xav"]
  end

  def contact

  end

  def gossip
    @gossip = Gossip.find(params[:id])
  end

  def user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    puts params[:user]
    # @user = User.new(name: params[:user][:name], password: params[:user][:password], city_id: params[:user][:city_id]) # avec xxx qui sont les données obtenues à partir du formulaire
    @user = User.new(post_params)
    if @user.save # essaie de sauvegarder en base @gossip
      redirect_to '/'
      # si ça marche, il redirige vers la page d'index du site
    else
      render "new"
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def post_params
    post_params = params.require(:user).permit(:name, :password, :city_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end
  
  def log_in(user)
    session[:user_id] = user.id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
  </head>
<header>
    <nav>
      <div class="nav-item">
        <%= link_to "ACCUEIL", gossips_path %>
      </div>
      <div class="nav-item">
        <%= link_to "TEAM", "/team" %>
      </div>
      <div class="nav-item">
        <%= link_to "CONTACT", "/contact" %>
      </div>
      <div class="nav-item">
        <%= link_to "VILLES", cities_path %>
      </div>
      <% if session[:user_id]  %>
        <div class="nav-item">
        <%= link_to "COMMENTAIRES", comments_path %>
      </div>
        <div class="nav-item">
          <%= link_to "Créer un potin", new_gossip_path %>
        </div>
        <div class="nav-item">
          <%= link_to "DECONNEXION", session_path(session.id), method: :delete %>
        </div>
      <%end%>
      <% if !session[:user_id]  %>
        <div class="dropdown">
          <button class="dropbtn">S'inscrire / Se connecter</button>
          <div class="dropdown-content">
            <a href="/users/new">INSCRIPTION</a>
            <a href="/sessions/new">CONNEXION</a>
          </div>
        </div>
      <%end%>
    </nav>
    
  </header>
  <% flash.each do |type, msg| %>
    <div class="alert alert-info">
      <%= msg %>
    </div>
  <% end %>
  <body>
    <%= yield %>
  </body>
  
</html>

app/views/pages/contact.html.erb
<div class="home">
  <h1>brice@nice.fr</h1>
</div>

app/views/pages/gossip.html.erb
<div class= "home">
  <h1>Gossip de <%=@gossip.user.name%></h1>

  <h2>Titre : <%=@gossip.title%> </h2>
  <h3>Gossip : <%=@gossip.content%> </h3>
  <p> <%=@gossip.created_at%> </p>
  <%= link_to "Afficher la page de l'utilisateur", "/users/#{@gossip.user_id}"%>
</div>

app/views/pages/home.html.erb
<h1>The Gossip Project</h1>
<div class="album-cards">
  <% @gossips.each do |gossip| %>
    <div class="card">
    <h3> <%=gossip.title%> </h3>
    <p>Ce gossip vous est servi par <%=gossip.user.name%></p>
    <%= link_to "Afficher le Gossip", "/tests/#{gossip.id}"%>
    </div>
  <%end%>
</div>

app/views/pages/team.html.erb
<div class="album-cards">
  <% @team.each do |current| %>
    <div class="card">
      <h3><%= current %></h3>
      <img src="<%= Faker::Avatar.image%>"/>
    </div>
  <% end %>
</div>

app/views/pages/user.html.erb
<div class="home">
  <h1>Page de <%=@user.name%> </h1>
  <ul>
    <li>L'utilisateur vit à <%=@user.city.name%></li>
    <li>L'utilisateur a écrit <%=@user.gossips.count%> gossip(s)</li>
    <li>L'utilisateur a donné <%=@user.likes.count%> like(s)</li>
  </ul>
  <img src="<%= Faker::Avatar.image%>"/>
</div>

app/views/pages/welcome.html.erb
<div class="home">
  <h1>SALUT</h1>
  <h2><%= @name %></h2>
  <h2><%= @path %></h2>
  <h2 class="alert">Et tu verras pas de connection à Bootstrap ici parcequ'on aime pas Bootstrap dans cette team !</h2>
</div>